-- +goose Up
ALTER TABLE source_event DROP CONSTRAINT IF EXISTS source_event_source_type_check;
ALTER TABLE source_event ADD CONSTRAINT source_event_source_type_check CHECK (source_type IN ('BANK_EMAIL', 'TELEGRAM_TEXT', 'TELEGRAM_CALLBACK', 'TELEGRAM_IMAGE', 'WEB_MANUAL', 'WEB_IMAGE', 'SYSTEM'));
ALTER TABLE job ADD COLUMN IF NOT EXISTS lane TEXT NOT NULL DEFAULT 'DEFAULT' CHECK (lane IN ('INTERACTIVE','DEFAULT','BACKGROUND'));
UPDATE job SET lane='INTERACTIVE' WHERE type IN ('PROCESS_TELEGRAM_CALLBACK','SEND_TELEGRAM_MESSAGE','EDIT_TELEGRAM_MESSAGE','PROCESS_TELEGRAM_REVIEW_TEXT');
UPDATE job SET lane='BACKGROUND' WHERE type IN ('FETCH_TELEGRAM_IMAGE','FINALIZE_TELEGRAM_MEDIA_GROUP','PROCESS_DOCUMENT','PROCESS_PAYSLIP','PROCESS_RECEIPT','PROCESS_TRANSACTION_SCREENSHOT','GENERATE_INSIGHT');
CREATE INDEX IF NOT EXISTS job_interactive_claim_idx ON job (run_after, created_at) WHERE status='PENDING' AND lane='INTERACTIVE';
CREATE INDEX IF NOT EXISTS job_default_claim_idx ON job (run_after, created_at) WHERE status='PENDING' AND lane='DEFAULT';
CREATE INDEX IF NOT EXISTS job_background_claim_idx ON job (run_after, created_at) WHERE status='PENDING' AND lane='BACKGROUND';

-- +goose Down
DROP INDEX IF EXISTS job_background_claim_idx;
DROP INDEX IF EXISTS job_default_claim_idx;
DROP INDEX IF EXISTS job_interactive_claim_idx;
ALTER TABLE job DROP COLUMN IF EXISTS lane;
ALTER TABLE source_event DROP CONSTRAINT IF EXISTS source_event_source_type_check;
ALTER TABLE source_event ADD CONSTRAINT source_event_source_type_check CHECK (source_type IN ('BANK_EMAIL', 'TELEGRAM_TEXT', 'TELEGRAM_IMAGE', 'WEB_MANUAL', 'WEB_IMAGE', 'SYSTEM'));
