-- +goose Up
ALTER TABLE job ADD COLUMN started_at TIMESTAMPTZ;
ALTER TABLE job ADD COLUMN finished_at TIMESTAMPTZ;

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION enforce_job_lane() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.lane := CASE
    WHEN NEW.type IN ('PROCESS_TELEGRAM_CALLBACK','SEND_TELEGRAM_MESSAGE','EDIT_TELEGRAM_MESSAGE','PROCESS_TELEGRAM_REVIEW_TEXT') THEN 'INTERACTIVE'
    WHEN NEW.type IN ('FETCH_TELEGRAM_IMAGE','FINALIZE_TELEGRAM_MEDIA_GROUP','PROCESS_DOCUMENT','PROCESS_PAYSLIP','PROCESS_RECEIPT','PROCESS_TRANSACTION_SCREENSHOT','GENERATE_INSIGHT','PROCESS_BANK_EMAIL') THEN 'BACKGROUND'
    ELSE 'DEFAULT'
  END;
  RETURN NEW;
END $$;
-- +goose StatementEnd

CREATE TRIGGER job_lane_enforcement BEFORE INSERT OR UPDATE OF type,lane ON job
FOR EACH ROW EXECUTE FUNCTION enforce_job_lane();

UPDATE job SET lane = CASE
  WHEN type IN ('PROCESS_TELEGRAM_CALLBACK','SEND_TELEGRAM_MESSAGE','EDIT_TELEGRAM_MESSAGE','PROCESS_TELEGRAM_REVIEW_TEXT') THEN 'INTERACTIVE'
  WHEN type IN ('FETCH_TELEGRAM_IMAGE','FINALIZE_TELEGRAM_MEDIA_GROUP','PROCESS_DOCUMENT','PROCESS_PAYSLIP','PROCESS_RECEIPT','PROCESS_TRANSACTION_SCREENSHOT','GENERATE_INSIGHT','PROCESS_BANK_EMAIL') THEN 'BACKGROUND'
  ELSE 'DEFAULT'
END
WHERE status IN ('PENDING','RUNNING');

-- +goose Down
DROP TRIGGER IF EXISTS job_lane_enforcement ON job;
DROP FUNCTION IF EXISTS enforce_job_lane();
ALTER TABLE job DROP COLUMN IF EXISTS finished_at;
ALTER TABLE job DROP COLUMN IF EXISTS started_at;
