-- +goose Up
-- Source-review completion is a user action and must not queue behind bank or
-- document extraction. Keep the durable lane classifier authoritative.
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION enforce_job_lane() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.lane := CASE
    WHEN NEW.type IN ('PROCESS_TELEGRAM_CALLBACK','SEND_TELEGRAM_MESSAGE','EDIT_TELEGRAM_MESSAGE','PROCESS_TELEGRAM_REVIEW_TEXT','COMPLETE_BANK_REVIEW') THEN 'INTERACTIVE'
    WHEN NEW.type IN ('FETCH_TELEGRAM_IMAGE','FINALIZE_TELEGRAM_MEDIA_GROUP','PROCESS_DOCUMENT','PROCESS_PAYSLIP','PROCESS_RECEIPT','PROCESS_TRANSACTION_SCREENSHOT','GENERATE_INSIGHT','PROCESS_BANK_EMAIL') THEN 'BACKGROUND'
    ELSE 'DEFAULT'
  END;
  RETURN NEW;
END $$;
-- +goose StatementEnd

UPDATE job SET lane='INTERACTIVE'
WHERE type='COMPLETE_BANK_REVIEW' AND status IN ('PENDING','RUNNING');

-- +goose Down
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION enforce_job_lane() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.lane := CASE
    WHEN NEW.type IN ('PROCESS_TELEGRAM_CALLBACK','SEND_TELEGRAM_MESSAGE','EDIT_TELEGRAM_MESSAGE','PROCESS_TELEGRAM_REVIEW_TEXT') THEN 'INTERACTIVE'
    WHEN NEW.type IN ('FETCH_TELEGRAM_IMAGE','FINALIZE_TELEGRAM_MEDIA_GROUP','PROCESS_DOCUMENT','PROCESS_PAYSLIP','PROCESS_RECEIPT','PROCESS_TRANSACTION_SCREENSHOT','GENERATE_INSIGHT','PROCESS_BANK_EMAIL') THEN 'BACKGROUND'
    ELSE 'DEFAULT'
  END;
  RETURN NEW;
END $$;
-- +goose StatementEnd
