-- +goose Up
ALTER TABLE financial_email_observation ADD COLUMN resolved_account_id UUID REFERENCES account(id);
ALTER TABLE financial_email_observation ADD COLUMN resolved_wealth_account_id UUID REFERENCES wealth_account(id);

ALTER TABLE review_item DROP CONSTRAINT review_item_review_type_check;
ALTER TABLE review_item ADD CONSTRAINT review_item_review_type_check CHECK (review_type IN ('UNKNOWN_MERCHANT','UNKNOWN_PURPOSE','AMBIGUOUS_CATEGORY','POSSIBLE_DUPLICATE','CONFLICTING_EVIDENCE','UNKNOWN_EMAIL_TEMPLATE','RECEIPT_MISMATCH','DOCUMENT_EXTRACTION_LOW_CONFIDENCE','TRANSFER_CLASSIFICATION','MANUAL_CORRECTION','DOCUMENT_CLASSIFICATION','PAYSLIP_CONFIRMATION','MISSING_PAY_DATE','SALARY_SOURCE_CONFIRMATION','UNKNOWN_BANK_TEMPLATE','INVOICE_PAYMENT_STATUS','CYCLE_RESIDUAL_ALLOCATION','WEALTH_OBSERVATION_CONFIRMATION','FINANCIAL_EMAIL_RESOLUTION'));
ALTER TABLE review_request DROP CONSTRAINT review_request_review_type_check;
ALTER TABLE review_request ADD CONSTRAINT review_request_review_type_check CHECK (review_type IN ('UNKNOWN_MERCHANT','UNKNOWN_PURPOSE','AMBIGUOUS_CATEGORY','POSSIBLE_DUPLICATE','CONFLICTING_EVIDENCE','UNKNOWN_EMAIL_TEMPLATE','RECEIPT_MISMATCH','DOCUMENT_EXTRACTION_LOW_CONFIDENCE','TRANSFER_CLASSIFICATION','MANUAL_CORRECTION','CYCLE_RESIDUAL_ALLOCATION','WEALTH_OBSERVATION_CONFIRMATION','FINANCIAL_EMAIL_RESOLUTION'));

-- +goose Down
DELETE FROM review_request_recipient WHERE review_request_id IN (SELECT rr.id FROM review_request rr JOIN review_item ri ON ri.id=rr.review_item_id WHERE ri.review_type='FINANCIAL_EMAIL_RESOLUTION');
DELETE FROM review_request WHERE review_item_id IN (SELECT id FROM review_item WHERE review_type='FINANCIAL_EMAIL_RESOLUTION');
DELETE FROM review_item WHERE review_type='FINANCIAL_EMAIL_RESOLUTION';
ALTER TABLE review_request DROP CONSTRAINT review_request_review_type_check;
ALTER TABLE review_request ADD CONSTRAINT review_request_review_type_check CHECK (review_type IN ('UNKNOWN_MERCHANT','UNKNOWN_PURPOSE','AMBIGUOUS_CATEGORY','POSSIBLE_DUPLICATE','CONFLICTING_EVIDENCE','UNKNOWN_EMAIL_TEMPLATE','RECEIPT_MISMATCH','DOCUMENT_EXTRACTION_LOW_CONFIDENCE','TRANSFER_CLASSIFICATION','MANUAL_CORRECTION','CYCLE_RESIDUAL_ALLOCATION','WEALTH_OBSERVATION_CONFIRMATION'));
ALTER TABLE review_item DROP CONSTRAINT review_item_review_type_check;
ALTER TABLE review_item ADD CONSTRAINT review_item_review_type_check CHECK (review_type IN ('UNKNOWN_MERCHANT','UNKNOWN_PURPOSE','AMBIGUOUS_CATEGORY','POSSIBLE_DUPLICATE','CONFLICTING_EVIDENCE','UNKNOWN_EMAIL_TEMPLATE','RECEIPT_MISMATCH','DOCUMENT_EXTRACTION_LOW_CONFIDENCE','TRANSFER_CLASSIFICATION','MANUAL_CORRECTION','DOCUMENT_CLASSIFICATION','PAYSLIP_CONFIRMATION','MISSING_PAY_DATE','SALARY_SOURCE_CONFIRMATION','UNKNOWN_BANK_TEMPLATE','INVOICE_PAYMENT_STATUS','CYCLE_RESIDUAL_ALLOCATION','WEALTH_OBSERVATION_CONFIRMATION'));
ALTER TABLE financial_email_observation DROP COLUMN resolved_wealth_account_id;
ALTER TABLE financial_email_observation DROP COLUMN resolved_account_id;
