-- +goose Up
-- SAVR-03: a screenshot row may genuinely have no visible amount. The
-- extraction represents that as null, and the row reaches review instead of
-- being coerced to a sentinel "0". The review reason names only that residual.
ALTER TABLE transaction_proposal ALTER COLUMN amount DROP NOT NULL;
ALTER TABLE transaction_proposal ADD CONSTRAINT transaction_proposal_missing_amount_check
    CHECK (amount IS NOT NULL OR proposal_status IN ('NEEDS_REVIEW','REJECTED'));
ALTER TABLE review_item DROP CONSTRAINT review_item_review_type_check;
ALTER TABLE review_item ADD CONSTRAINT review_item_review_type_check CHECK (review_type IN (
    'UNKNOWN_MERCHANT','UNKNOWN_PURPOSE','AMBIGUOUS_CATEGORY','POSSIBLE_DUPLICATE',
    'CONFLICTING_EVIDENCE','UNKNOWN_EMAIL_TEMPLATE','RECEIPT_MISMATCH',
    'DOCUMENT_EXTRACTION_LOW_CONFIDENCE','TRANSFER_CLASSIFICATION','MANUAL_CORRECTION',
    'DOCUMENT_CLASSIFICATION','PAYSLIP_CONFIRMATION','MISSING_PAY_DATE',
    'SALARY_SOURCE_CONFIRMATION','UNKNOWN_BANK_TEMPLATE','INVOICE_PAYMENT_STATUS',
    'CYCLE_RESIDUAL_ALLOCATION','WEALTH_OBSERVATION_CONFIRMATION',
    'FINANCIAL_EMAIL_RESOLUTION','MISSING_TRANSACTION_DATE','TRANSACTION_FACTS_MISSING',
    'MISSING_AMOUNT'
));
ALTER TABLE review_request DROP CONSTRAINT review_request_review_type_check;
ALTER TABLE review_request ADD CONSTRAINT review_request_review_type_check CHECK (review_type IN (
    'UNKNOWN_MERCHANT','UNKNOWN_PURPOSE','AMBIGUOUS_CATEGORY','POSSIBLE_DUPLICATE',
    'CONFLICTING_EVIDENCE','UNKNOWN_EMAIL_TEMPLATE','RECEIPT_MISMATCH',
    'DOCUMENT_EXTRACTION_LOW_CONFIDENCE','TRANSFER_CLASSIFICATION','MANUAL_CORRECTION',
    'DOCUMENT_CLASSIFICATION','PAYSLIP_CONFIRMATION','MISSING_PAY_DATE',
    'SALARY_SOURCE_CONFIRMATION','UNKNOWN_BANK_TEMPLATE','INVOICE_PAYMENT_STATUS',
    'CYCLE_RESIDUAL_ALLOCATION','WEALTH_OBSERVATION_CONFIRMATION',
    'FINANCIAL_EMAIL_RESOLUTION','MISSING_TRANSACTION_DATE','TRANSACTION_FACTS_MISSING',
    'MISSING_AMOUNT'
));

-- +goose Down
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM transaction_proposal WHERE amount IS NULL) THEN
        RAISE EXCEPTION 'cannot roll back missing amounts while unresolved proposals exist';
    END IF;
    IF EXISTS (SELECT 1 FROM review_item WHERE review_type='MISSING_AMOUNT')
       OR EXISTS (SELECT 1 FROM review_request WHERE review_type='MISSING_AMOUNT') THEN
        RAISE EXCEPTION 'cannot roll back MISSING_AMOUNT while reviews still use it';
    END IF;
END $$;
ALTER TABLE transaction_proposal DROP CONSTRAINT transaction_proposal_missing_amount_check;
ALTER TABLE transaction_proposal ALTER COLUMN amount SET NOT NULL;
ALTER TABLE review_item DROP CONSTRAINT review_item_review_type_check;
ALTER TABLE review_item ADD CONSTRAINT review_item_review_type_check CHECK (review_type IN (
    'UNKNOWN_MERCHANT','UNKNOWN_PURPOSE','AMBIGUOUS_CATEGORY','POSSIBLE_DUPLICATE',
    'CONFLICTING_EVIDENCE','UNKNOWN_EMAIL_TEMPLATE','RECEIPT_MISMATCH',
    'DOCUMENT_EXTRACTION_LOW_CONFIDENCE','TRANSFER_CLASSIFICATION','MANUAL_CORRECTION',
    'DOCUMENT_CLASSIFICATION','PAYSLIP_CONFIRMATION','MISSING_PAY_DATE',
    'SALARY_SOURCE_CONFIRMATION','UNKNOWN_BANK_TEMPLATE','INVOICE_PAYMENT_STATUS',
    'CYCLE_RESIDUAL_ALLOCATION','WEALTH_OBSERVATION_CONFIRMATION',
    'FINANCIAL_EMAIL_RESOLUTION','MISSING_TRANSACTION_DATE','TRANSACTION_FACTS_MISSING'
));
ALTER TABLE review_request DROP CONSTRAINT review_request_review_type_check;
ALTER TABLE review_request ADD CONSTRAINT review_request_review_type_check CHECK (review_type IN (
    'UNKNOWN_MERCHANT','UNKNOWN_PURPOSE','AMBIGUOUS_CATEGORY','POSSIBLE_DUPLICATE',
    'CONFLICTING_EVIDENCE','UNKNOWN_EMAIL_TEMPLATE','RECEIPT_MISMATCH',
    'DOCUMENT_EXTRACTION_LOW_CONFIDENCE','TRANSFER_CLASSIFICATION','MANUAL_CORRECTION',
    'DOCUMENT_CLASSIFICATION','PAYSLIP_CONFIRMATION','MISSING_PAY_DATE',
    'SALARY_SOURCE_CONFIRMATION','UNKNOWN_BANK_TEMPLATE','INVOICE_PAYMENT_STATUS',
    'CYCLE_RESIDUAL_ALLOCATION','WEALTH_OBSERVATION_CONFIRMATION',
    'FINANCIAL_EMAIL_RESOLUTION','MISSING_TRANSACTION_DATE','TRANSACTION_FACTS_MISSING'
));
