"use client";

import { useCallback, useEffect, useState } from "react";
import AppShell from "../components/AppShell";
import useAuth from "../components/useAuth";
import { ErrorNotice, Skeleton } from "../components/Feedback";
import { money, dateTime } from "../lib/format";
import { NetWorthHistoryChart } from "../components/Charts";

const empty = { accounts: [], snapshots: [], latest: null, previous: null, summary: null, currentCycle: null, cycleRecaps: [], observation: null };

export function jakartaDateTimeLocal(date = new Date()) {
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Jakarta", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(date);
  const value = Object.fromEntries(parts.map(part => [part.type, part.value]));
  return `${value.year}-${value.month}-${value.day}T${value.hour}:${value.minute}`;
}

export function jakartaLocalToRFC3339(value) {
  return `${value}:00+07:00`;
}

export default function WealthPage() {
  const user = useAuth();
  const [data, setData] = useState(empty), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState(null), [working, setWorking] = useState(false);
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try { const observationId = new URLSearchParams(window.location.search).get("observationId"); const [accountsResponse, summaryResponse, latestResponse, historyResponse, currentCycleResponse, cycleRecapsResponse, observationResponse] = await Promise.all([fetch("/api/v1/wealth/accounts"), fetch("/api/v1/wealth/summary"), fetch("/api/v1/wealth/snapshots/latest"), fetch("/api/v1/wealth/history"), fetch("/api/v1/wealth/current-cycle-savings"), fetch("/api/v1/wealth/cycle-recaps"), observationId ? fetch(`/api/v1/wealth/observations/${observationId}`) : Promise.resolve(null)]); if (![accountsResponse, summaryResponse, latestResponse, historyResponse, currentCycleResponse, cycleRecapsResponse].every(response => response.ok) || observationResponse && !observationResponse.ok) throw new Error(); const [accounts, summary, latest, snapshots, currentCycle, cycleRecaps, observation] = await Promise.all([accountsResponse.json(), summaryResponse.json(), latestResponse.json(), historyResponse.json(), currentCycleResponse.json(), cycleRecapsResponse.json(), observationResponse ? observationResponse.json() : null]); setData({ ...empty, accounts: Array.isArray(accounts) ? accounts : [], snapshots: Array.isArray(snapshots) ? snapshots : [], latest: latest || summary?.latest || null, previous: summary?.previous || null, summary, currentCycle, cycleRecaps: Array.isArray(cycleRecaps) ? cycleRecaps : [], observation }); }
    catch { setError("Data Wealth belum dapat dimuat. Coba lagi."); } finally { setLoading(false); }
  }, []);
  useEffect(() => { if (user) load(); }, [user, load]);
  async function saveSnapshot(event) { event.preventDefault(); setWorking(true); const form = new FormData(event.currentTarget); const items = data.accounts.filter(item => item.active !== false).map(item => { const result = { wealthAccountId: item.id, valueIdr: form.get(`value-${item.id}`), source: "MANUAL", note: form.get(`note-${item.id}`) || null }; if (data.observation?.resolvedWealthAccountId === item.id) result.source = "DOCUMENT"; return result; }); const observedAt = jakartaLocalToRFC3339(form.get("observedAt")); const response = await fetch("/api/v1/wealth/snapshots", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ observedAt, observationId: data.observation?.id || null, items }) }); if (!response.ok) setError("Snapshot belum dapat disimpan."); else { window.history.replaceState({}, "", "/wealth"); await load(); } setWorking(false); }
  async function openSnapshot(id) { setError(""); const response = await fetch(`/api/v1/wealth/snapshots/${id}`); if (!response.ok) { setError("Detail snapshot belum dapat dimuat."); return; } setSelected(await response.json()); }
  if (user === null) return <main className="loading">Memuat…</main>;
  if (!user) return null;
  const latest = data.latest || data.snapshots?.[0];
  const previousValues = new Map((latest?.items || []).map(item => [item.wealthAccountId, item.valueIdr])); if (data.observation?.resolvedWealthAccountId) previousValues.set(data.observation.resolvedWealthAccountId, data.observation.observedValueIdr);
  const assets = (latest?.items || []).filter(item => item.side === "ASSET");
  const liabilities = (latest?.items || []).filter(item => item.side === "LIABILITY");
  return <AppShell user={user} eyebrow="WEALTH" title="Wealth dan kekayaan bersih" actions={<a className="button secondary" href="/settings#wealth-accounts">Kelola akun Wealth</a>}>
    <ErrorNotice message={error} retry={load}/>{loading ? <Skeleton cards={3} rows={3}/> : <>
      {!latest ? <section className="surface empty-state"><h2>Kekayaan belum diatur</h2><p>Buat snapshot awal lengkap untuk mulai melihat Net Worth.</p></section> : <><section className="wealth-kpis"><article><span>Kekayaan bersih terakhir</span><strong>{money(latest.netWorthIdr)}</strong><small>Snapshot {dateTime(latest.observedAt)}</small></article><article><span>Aset</span><strong className="positive">{money(latest.assetTotalIdr)}</strong><small>Nilai observasi</small></article><article><span>Kewajiban</span><strong className="negative">{money(latest.liabilityTotalIdr)}</strong><small>Nilai observasi</small></article></section><section className="surface wealth-section"><div className="section-title"><div><span className="eyebrow">POSISI TERAKHIR</span><h2>Aset dan kewajiban</h2></div></div><div className="wealth-detail-row"><b>Aset</b><span>{assets.map(item => `${item.name} ${money(item.valueIdr)}`).join(" · ") || "—"}</span></div><div className="wealth-detail-row"><b>Kewajiban</b><span>{liabilities.map(item => `${item.name} ${money(item.valueIdr)}`).join(" · ") || "—"}</span></div></section></>}
      {data.summary?.previous && <section className="wealth-kpis"><article><span>Perubahan Net Worth</span><strong>{money(data.summary.netWorthChangeIdr)}</strong></article><article><span>Cashflow terkonfirmasi</span><strong>{money(data.summary.confirmedCashflowIdr)}</strong></article><article><span>Valuasi / perubahan lain</span><strong>{money(data.summary.valuationAndOtherChangeIdr)}</strong></article></section>}
      {data.snapshots.length > 1 && <section className="surface wealth-section"><div className="section-title"><div><span className="eyebrow">RIWAYAT NET WORTH</span><h2>Perubahan dari waktu ke waktu</h2></div></div><NetWorthHistoryChart items={data.snapshots}/></section>}
      {data.currentCycle && <section className="surface wealth-section"><div className="section-title"><div><span className="eyebrow">{data.currentCycle.periodKind === "CURRENT_CYCLE" ? "TABUNGAN SIKLUS BERJALAN" : "TABUNGAN BULAN INI"}</span><h2>{money(data.currentCycle.savingsAllocated)}</h2></div><span className="header-meta">{data.currentCycle.periodStart} – {data.currentCycle.periodEnd}</span></div>{(data.currentCycle.savingsByDestination || []).map(item => <div className="wealth-detail-row" key={item.wealthAccountId || item.name}><span>{item.name}</span><strong>{money(item.amountIdr)}</strong></div>)}</section>}
      <section className="surface wealth-section"><div className="section-title"><div><span className="eyebrow">SNAPSHOT</span><h2>{latest ? "Perbarui posisi Wealth" : "Buat snapshot awal"}</h2></div><span className="header-meta">Snapshot lengkap · Asia/Jakarta</span></div>{data.observation?.observedDate && <p className="muted">Nilai dokumen bertanggal {data.observation.observedDate}. Pilih waktu observasi sebelum menyimpan; waktu tidak ditebak dari dokumen.</p>}<form key={latest?.id || "initial"} className="wealth-snapshot-form" onSubmit={saveSnapshot}><label>Waktu observasi<input name="observedAt" type="datetime-local" required defaultValue={data.observation?.observedDate ? "" : jakartaDateTimeLocal()}/></label>{data.accounts.filter(item => item.active !== false).map(item => <label key={item.id}>{item.name}<small>{item.institution || item.wealthType || item.usageRole}</small><input name={`value-${item.id}`} inputMode="numeric" pattern="[0-9]+" placeholder="Nilai IDR" required defaultValue={previousValues.get(item.id) || ""}/><input name={`note-${item.id}`} placeholder="Catatan (opsional)"/></label>)}{!data.accounts.length && <p className="empty compact">Belum ada Wealth Account. Tambahkan di Pengaturan.</p>}<button disabled={working || !data.accounts.length}>{working ? "Menyimpan…" : "Simpan snapshot lengkap"}</button></form></section>
      {data.cycleRecaps.length > 0 && <section className="surface wealth-section"><div className="section-title"><div><span className="eyebrow">SIKLUS TABUNGAN</span><h2>Rekap siklus tertutup</h2></div></div>{data.cycleRecaps.map(cycle => <article className="wealth-history-row" key={`${cycle.cycleStart}-${cycle.cycleEnd}`}><span>{cycle.cycleStart} – {cycle.cycleEnd}</span><b>Surplus {money(cycle.cashflowSurplus)}</b><small>Dialokasikan {money(cycle.savingsAllocated)} · Belum dialokasikan {money(cycle.rawResidual)} · {cycle.residualReviewStatus}</small><small>{(cycle.savingsByDestination || []).map(item => `${item.name}: ${money(item.amountIdr)}`).join(" · ") || "Belum ada tujuan tabungan"}</small></article>)}</section>}
      <section className="surface wealth-section"><div className="section-title"><div><span className="eyebrow">RIWAYAT</span><h2>Snapshot tersimpan</h2></div></div><div className="wealth-history">{data.snapshots.map(item => <button key={item.id} className="wealth-history-row" onClick={() => openSnapshot(item.id)}><span>{dateTime(item.observedAt)}</span><b>{money(item.netWorthIdr || "0")}</b><small>Lihat rincian akun</small></button>)}{!data.snapshots.length && <p className="empty compact">Belum ada snapshot Wealth.</p>}</div></section>
    </>}{selected && <div className="drawer-backdrop" onClick={() => setSelected(null)}><aside className="detail-drawer" onClick={event => event.stopPropagation()}><button className="drawer-close" aria-label="Tutup detail" onClick={() => setSelected(null)}>×</button><span className="eyebrow">DETAIL SNAPSHOT</span><h2>{dateTime(selected.observedAt)}</h2>{(selected.items || []).map(item => <div className="wealth-detail-row" key={item.id || item.wealthAccountId}><span>{item.name || item.accountName}</span><strong>{money(item.valueIdr)}</strong></div>)}</aside></div>}
  </AppShell>;
}
