package admin

import (
 "encoding/json"; "net/http"; "strings"
 "github.com/jackc/pgx/v5/pgxpool"
 "github.com/raufimusaddiq/richmod/apps/api/internal/auth"
)
type Handler struct{ pool *pgxpool.Pool }
func NewHandler(p *pgxpool.Pool)*Handler{return &Handler{p}}
func (h *Handler) Require(next http.Handler) http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){p,ok:=auth.PrincipalFromContext(r.Context());if !ok||!p.IsSuperAdmin{http.Error(w,`{"error":"super admin required"}`,403);return};next.ServeHTTP(w,r)})}
func (h *Handler) Users(w http.ResponseWriter,r *http.Request){rows,err:=h.pool.Query(r.Context(),`SELECT id,email,display_name,active,is_super_admin,password_initialized_at FROM "user" ORDER BY created_at`);if err!=nil{http.Error(w,"{}",500);return};defer rows.Close(); out:=[]map[string]any{};for rows.Next(){var id,email,name string;var active,sa bool;var init any; if rows.Scan(&id,&email,&name,&active,&sa,&init)==nil{out=append(out,map[string]any{"id":id,"email":email,"displayName":name,"active":active,"isSuperAdmin":sa,"passwordInitialized":init!=nil})}};json.NewEncoder(w).Encode(out)}
func (h *Handler) Households(w http.ResponseWriter,r *http.Request){rows,err:=h.pool.Query(r.Context(),`SELECT id,name,timezone FROM household ORDER BY created_at`);if err!=nil{http.Error(w,"{}",500);return};defer rows.Close();out:=[]map[string]string{};for rows.Next(){var id,n,t string;if rows.Scan(&id,&n,&t)==nil{out=append(out,map[string]string{"id":id,"name":n,"timezone":t})}};json.NewEncoder(w).Encode(out)}
func (h *Handler) PatchUser(w http.ResponseWriter,r *http.Request){id:=r.PathValue("id");var in struct{Active *bool `json:"active"`; IsSuperAdmin *bool `json:"isSuperAdmin"`};if json.NewDecoder(r.Body).Decode(&in)!=nil{http.Error(w,"{}",400);return};if id==""{http.Error(w,"{}",400);return};if in.Active!=nil{_,_=h.pool.Exec(r.Context(),`UPDATE "user" SET active=$1,updated_at=now() WHERE id=$2`,*in.Active,id)};if in.IsSuperAdmin!=nil{_,_=h.pool.Exec(r.Context(),`UPDATE "user" SET is_super_admin=$1,updated_at=now() WHERE id=$2`,*in.IsSuperAdmin,id)};w.WriteHeader(204)}
func (h *Handler) Members(w http.ResponseWriter,r *http.Request){hid:=r.PathValue("householdId");rows,err:=h.pool.Query(r.Context(),`SELECT u.id,u.email,u.display_name,hm.role,hm.active FROM household_member hm JOIN "user" u ON u.id=hm.user_id WHERE hm.household_id=$1 ORDER BY u.email`,hid);if err!=nil{http.Error(w,"{}",500);return};defer rows.Close();out:=[]map[string]any{};for rows.Next(){var id,e,n,role string;var a bool;if rows.Scan(&id,&e,&n,&role,&a)==nil{out=append(out,map[string]any{"id":id,"email":e,"displayName":n,"role":role,"active":a})}};json.NewEncoder(w).Encode(out)}
func (h *Handler) AddMember(w http.ResponseWriter,r *http.Request){hid:=r.PathValue("householdId");var in struct{Email,DisplayName string};if json.NewDecoder(r.Body).Decode(&in)!=nil||!strings.Contains(in.Email,"@"){http.Error(w,"{}",400);return};var id string;err:=h.pool.QueryRow(r.Context(),`INSERT INTO "user"(email,display_name,password_hash) VALUES(lower($1),$2,'!') RETURNING id`,in.Email,in.DisplayName).Scan(&id);if err!=nil{http.Error(w,"{}",409);return};if _,err=h.pool.Exec(r.Context(),`INSERT INTO household_member(household_id,user_id,role) VALUES($1,$2,'MEMBER')`,hid,id);err!=nil{http.Error(w,"{}",500);return};w.WriteHeader(201)}
