import { useState } from "react";
import { money } from "../../lib/format";
import { reviewTypes, label, ProposalFacts } from "./shared";
import FinancialEmailResolutionCard from "./FinancialEmailResolutionCard";
import TransferReconciliationCard from "./TransferReconciliationCard";
import WealthObservationCard from "./WealthObservationCard";
import ResidualCard from "./ResidualCard";

export default function CanonicalCard({ item, categories, accounts, wealthAccounts, disabled, action }) {
  const [editing, setEditing] = useState(false);
  const payslip = item.reviewType === "PAYSLIP_CONFIRMATION"; const missingDate = item.reviewType === "MISSING_PAY_DATE"; const salaryChoice = item.allowedActions?.includes("PRIMARY_SALARY") || item.allowedActions?.includes("ORDINARY_INCOME"); const residual = item.reviewType === "CYCLE_RESIDUAL_ALLOCATION"; const wealthObservation = item.reviewType === "WEALTH_OBSERVATION_CONFIRMATION"; const bankFacts = item.allowedActions?.includes("COMPLETE_BANK_FACTS"); const reprocessDocument = item.allowedActions?.includes("REPROCESS_DOCUMENT");
  function resolve(actionName, values = {}) { action(item.id, "resolve", { action: actionName, values }); }
  function submitDate(event) { event.preventDefault(); const form = new FormData(event.currentTarget); resolve("SET_PAY_DATE", { payDate: form.get("payDate"), ...(salaryChoice ? { choice: form.get("choice") } : {}) }); }
  function submitBank(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const raw = form.get("transactionAt"); resolve("COMPLETE_BANK_FACTS", { amountIdr: form.get("amountIdr") || null, transactionAt: raw ? new Date(raw).toISOString() : null }); }
  if (residual) return <ResidualCard item={item} wealthAccounts={wealthAccounts} disabled={disabled} resolve={resolve}/>;
  if (wealthObservation) return <WealthObservationCard item={item} wealthAccounts={wealthAccounts} disabled={disabled} resolve={resolve}/>;
  if (item.reviewType === "FINANCIAL_EMAIL_RESOLUTION") return <FinancialEmailResolutionCard item={item} accounts={accounts} wealthAccounts={wealthAccounts} disabled={disabled} resolve={resolve}/>;
  if (item.reviewType === "TRANSFER_CLASSIFICATION" && item.transferCandidates?.length) return <TransferReconciliationCard item={item} disabled={disabled} resolve={resolve}/>;
  // Proposal-first: the card states what happened, what Richmod proposes, and
  // the single unresolved dimension, then offers one primary accept action.
  const missing = item.missingFacts || [];
  if (item.reviewType === "MISSING_AMOUNT") return <article className="review-card"><div className="review-top"><span className="review-reason">{reviewTypes.MISSING_AMOUNT}</span></div><h2>{item.description || item.knownFacts?.merchant || "Transaksi dari tangkapan layar"}</h2><ProposalFacts item={item} known={Object.entries(item.knownFacts || {})} missing={missing}/><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); resolve("SET_AMOUNT", { amountIdr: form.get("amountIdr"), ...(missing.includes("category") ? { categoryId: form.get("categoryId") } : {}), ...(missing.includes("transaction_at") ? { transactionDate: form.get("transactionDate") } : {}), ...(missing.includes("transfer_relationship") ? { incomeConfirmed: form.get("incomeConfirmed") === "on" } : {}) }); }}><label>Jumlah (IDR)<input name="amountIdr" inputMode="numeric" pattern="[0-9]+" maxLength={20} required autoComplete="off"/></label>{missing.includes("category") && <label>Kategori<select name="categoryId" required defaultValue=""><option value="" disabled>Pilih kategori</option>{categories.filter(category => category.active).map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label>}{missing.includes("transaction_at") && <label>Tanggal transaksi<input name="transactionDate" type="date" required/></label>}{missing.includes("transfer_relationship") && <label className="check review-check"><input name="incomeConfirmed" type="checkbox" required/> Ini penghasilan, bukan transfer milik sendiri</label>}<div className="review-actions"><button disabled={disabled}>Simpan transaksi</button><button type="button" className="danger" disabled={disabled} onClick={() => resolve("IGNORE")}>Abaikan</button></div></form></article>;
  if (payslip) { const canPrimary = item.allowedActions?.includes("PRIMARY_SALARY"); return <article className="review-card"><div className="review-top"><span className="review-reason">{reviewTypes[item.reviewType]}</span>{item.amount && <strong>{money(item.amount)}</strong>}</div><h2>{item.description || "Slip gaji perlu dikonfirmasi"}</h2><ProposalFacts item={item} known={[]} missing={missing}/><p>{canPrimary ? "Ini penerimaan pertama dari sumber gaji ini. Pilih cara mencatatnya." : "Slip gaji ini akan dicatat sebagai pemasukan."}</p><div className="transfer-options">{canPrimary && <button disabled={disabled} onClick={() => resolve("PRIMARY_SALARY")}>Gaji utama</button>}<button disabled={disabled} onClick={() => resolve("ORDINARY_INCOME")}>Pemasukan biasa</button><button className="danger" disabled={disabled} onClick={() => resolve("IGNORE")}>Abaikan</button></div></article>; }
  if (missingDate) return <article className="review-card"><div className="review-top"><span className="review-reason">{reviewTypes[item.reviewType]}</span>{item.amount && <strong>{money(item.amount)}</strong>}</div><h2>{item.description || "Tanggal pembayaran belum ada"}</h2><ProposalFacts item={item} known={[]} missing={missing.length ? missing : ["transaction_at"]}/>{!editing ? <div className="review-actions"><button disabled={disabled} onClick={() => setEditing(true)}>Isi tanggal</button><button className="danger" disabled={disabled} onClick={() => resolve("IGNORE")}>Abaikan</button></div> : <form onSubmit={submitDate}><label>Tanggal pembayaran<input name="payDate" type="date" required/></label>{salaryChoice && <label>Catat sebagai<select name="choice" defaultValue="ORDINARY_INCOME"><option value="ORDINARY_INCOME">Pemasukan biasa</option><option value="PRIMARY_SALARY">Gaji utama</option></select></label>}<div className="review-actions"><button disabled={disabled}>Simpan dan konfirmasi</button><button type="button" className="secondary" disabled={disabled} onClick={() => setEditing(false)}>Batal</button></div></form>}</article>;
  return <article className="review-card"><div className="review-top"><span className="review-reason">{reviewTypes[item.reviewType] || item.reviewType.replaceAll("_", " ")}</span>{item.amount && <strong>{money(item.amount)}</strong>}</div><h2>{item.description || "Bukti keuangan perlu ditinjau"}</h2><ProposalFacts item={item} known={[]} missing={missing}/>{bankFacts && !editing && <div className="review-actions"><button disabled={disabled} onClick={() => setEditing(true)}>Lengkapi detail</button><button className="danger" disabled={disabled} onClick={() => resolve("IGNORE")}>Abaikan</button></div>}{bankFacts && editing && <form onSubmit={submitBank}><label>Jumlah (IDR)<input name="amountIdr" inputMode="numeric" pattern="[0-9]+" defaultValue={item.amount || ""}/></label><label>Waktu transaksi<input name="transactionAt" type="datetime-local"/></label><p className="muted">Gunakan waktu yang tercantum pada bukti. Sistem menyimpan waktu Indonesia.</p><div className="review-actions"><button disabled={disabled}>Lengkapi transaksi</button><button type="button" className="secondary" disabled={disabled} onClick={() => setEditing(false)}>Batal</button></div></form>}{reprocessDocument && <div className="review-actions"><button disabled={disabled} onClick={() => resolve("REPROCESS_DOCUMENT")}>Proses ulang</button><button className="danger" disabled={disabled} onClick={() => resolve("IGNORE")}>Abaikan</button></div>}{!payslip && !missingDate && !bankFacts && !reprocessDocument && <div className="review-actions"><button className="danger" disabled={disabled} onClick={() => resolve("IGNORE")}>Abaikan</button></div>}</article>;
}
