import Link from "next/link";
import { useState } from "react";
import { dateTime, money } from "../../lib/format";
import { ProposalFacts } from "./shared";

export default function TransferCard({ item, categories, wealthAccounts, disabled, action }) {
  const [editing, setEditing] = useState(false);
  function expense(event) { event.preventDefault(); const form = new FormData(event.currentTarget); action(item.id, "classify-transfer", { classification: "EXPENSE", categoryId: form.get("categoryId") }); }
  function assetPurchase(event) { event.preventDefault(); const form = new FormData(event.currentTarget); action(item.id, "classify-transfer", { classification: "ASSET_PURCHASE", wealthAccountId: form.get("wealthAccountId") }); }
  return <article className="review-card transfer-card"><div className="review-top"><span className="review-reason">Transfer belum dikenal</span><strong>{money(item.amount)}</strong></div><h2>{item.counterparty || "Tujuan transfer belum dikenal"}</h2><p>{dateTime(item.transactionAt)} · belum dihitung sebagai pengeluaran</p><ProposalFacts item={item} known={[["amount_idr", money(item.amount)], ["merchant", item.counterparty]]} missing={item.missingFacts || ["transfer_relationship"]}/><p>Pilih jenisnya, atau lengkapi detail bila ini pengeluaran atau pembelian aset.</p><div className="transfer-options"><button disabled={disabled} onClick={() => action(item.id, "classify-transfer", { classification: "OWN_ACCOUNT" })}>Rekening sendiri</button><button disabled={disabled} onClick={() => action(item.id, "classify-transfer", { classification: "HOUSEHOLD_ACCOUNT" })}>Rekening rumah tangga</button><button disabled={disabled} onClick={() => action(item.id, "classify-transfer", { classification: "INVESTMENT_ACCOUNT" })}>Investasi / RDN</button><button className="secondary" disabled={disabled} onClick={() => setEditing(true)}>Ubah detail</button><button className="danger" disabled={disabled} onClick={() => action(item.id, "classify-transfer", { classification: "IGNORE" })}>Abaikan</button></div>{editing && <form onSubmit={assetPurchase}><label>Beli aset<select name="wealthAccountId" required defaultValue=""><option value="" disabled>Pilih akun kekayaan</option>{wealthAccounts.filter(account => account.active && account.side === "ASSET").map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><button disabled={disabled}>Beli aset</button></form>}{editing && <form onSubmit={expense}><label>Jika ini pengeluaran<select name="categoryId" required defaultValue=""><option value="" disabled>Pilih kategori</option>{categories.filter(category => category.active).map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><div className="review-actions"><button disabled={disabled}>Catat sebagai pengeluaran</button><Link className="button secondary" href={`/transactions?id=${item.id}`}>Bukti</Link></div></form>}</article>;
}
