"use client";

import { useCallback, useEffect, useState } from "react";
import AppShell from "../components/AppShell";
import useAuth from "../components/useAuth";
import { dateTime } from "../lib/format";

export default function SettingsPage() {
  const user = useAuth();
  const [data, setData] = useState({ accounts: [], categories: [], aliases: [], known: [], members: [], operations: null, salarySources: [], listeners: [], emailIngress: null });
  const [error, setError] = useState(""); const [working, setWorking] = useState("");
  const owner = user?.household?.role === "OWNER";
  const load = useCallback(async () => {
    const endpoints = ["accounts", "categories", "merchant-aliases", "known-accounts", "household/members", "operations/status", "salary/sources", "bank-email-listeners", "integrations/email-ingress"];
    const responses = await Promise.all(endpoints.map(value => fetch(`/api/v1/${value}`)));
    const values = await Promise.all(responses.map(response => response.ok ? response.json() : null));
    setData({ accounts: values[0] || [], categories: values[1] || [], aliases: values[2] || [], known: values[3] || [], members: values[4] || [], operations: values[5], salarySources: values[6] || [], listeners: values[7] || [], emailIngress: values[8] });
  }, []);
  useEffect(() => { if (user) load(); }, [user, load]);

  async function request(key, url, options) { setWorking(key); setError(""); const response = await fetch(url, options); if (!response.ok) { const body = await response.json().catch(() => ({})); setError(body.error || "Perubahan belum dapat disimpan."); } else await load(); setWorking(""); return response.ok; }
  async function createAccount(event) { event.preventDefault(); const form = new FormData(event.currentTarget); if (await request("account-new", "/api/v1/accounts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), accountType: form.get("accountType"), trackingPolicy: form.get("trackingPolicy") }) })) event.currentTarget.reset(); }
  async function createCategory(event) { event.preventDefault(); const form = new FormData(event.currentTarget); if (await request("category-new", "/api/v1/categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), slug: form.get("slug"), parentId: form.get("parentId") || null }) })) event.currentTarget.reset(); }
  async function createKnown(event) { event.preventDefault(); const form = new FormData(event.currentTarget); if (await request("known-new", "/api/v1/known-accounts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ institution: form.get("institution"), displayName: form.get("displayName"), matchHint: form.get("matchHint"), relationship: form.get("relationship"), userId: form.get("userId") || null }) })) event.currentTarget.reset(); }
  function selectSalary(event) { request("salary-source", "/api/v1/salary/sources", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sourceId: event.target.value }) }); }
  async function createListener(event) { event.preventDefault(); const form = new FormData(event.currentTarget); if (await request("listener-new", "/api/v1/bank-email-listeners", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ bankName: form.get("bankName"), senderAddress: form.get("senderAddress") }) })) event.currentTarget.reset(); }
  const emailIngressAction = (action = "") => request(`email-ingress-${action || "create"}`, `/api/v1/integrations/email-ingress${action ? `/${action}` : ""}`, { method: "POST" });
  async function copyEmailIngress() { try { await navigator.clipboard.writeText(data.emailIngress.address); } catch { setError("Alamat email tidak dapat disalin. Salin manual dari teks di atas."); } }
  const patch = (key, path, body) => request(key, `/api/v1/${path}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  function rename(item, kind) { const name = window.prompt(`Nama ${kind} baru`, item.name); if (name?.trim() && name.trim() !== item.name) patch(item.id, `${kind === "rekening" ? "accounts" : "categories"}/${item.id}`, { name: name.trim() }); }
  if (!user) return <main className="loading">Memuat…</main>;
  return <AppShell user={user} eyebrow="PENGATURAN" title="Pengaturan keluarga" actions={<span className="header-meta">{owner ? "Akses pemilik" : "Hanya baca"}</span>}>
    {error && <p className="notice error">{error}</p>}
    <div className="settings-sections">
      <SettingsSection eyebrow="REKENING MANUAL" title="Rekening manual" description="Kelola rekening yang tidak terhubung ke notifikasi email bank. Atur kebijakan pencatatannya untuk buku keluarga.">
        {owner && <form className="inline-form" onSubmit={createAccount}><input name="name" placeholder="Nama rekening" required/><select name="accountType" defaultValue="BANK"><option value="BANK">Bank</option><option value="CASH">Tunai</option><option value="EWALLET">Dompet Digital</option><option value="OTHER">Lainnya</option></select><select name="trackingPolicy" defaultValue="SPENDING_ONLY"><option value="SPENDING_ONLY">Pengeluaran Saja</option><option value="FULL_LEDGER">Buku Besar Lengkap</option><option value="REFERENCE_ONLY">Referensi Saja</option></select><button disabled={working === "account-new"}>Tambah</button></form>}
        <div className="settings-list">{data.accounts.map(item => <article key={item.id}><div><b>{item.name}</b><small>{item.accountType}{item.systemManaged ? " · Dikelola email" : " · Manual"}</small></div><span>{({SPENDING_ONLY: "Pengeluaran Saja", FULL_LEDGER: "Buku Besar Lengkap", REFERENCE_ONLY: "Referensi Saja"})[item.trackingPolicy] || item.trackingPolicy} · Tidak dapat diubah</span>{owner && !item.systemManaged && <div className="row-actions"><button className="secondary" onClick={() => rename(item, "rekening")}>Ubah nama</button><button className={item.active ? "danger" : "secondary"} onClick={() => patch(item.id, `accounts/${item.id}`, { active: !item.active })}>{item.active ? "Nonaktifkan" : "Aktifkan"}</button></div>}</article>)}{!data.accounts.length && <p className="empty compact">Belum ada rekening. Tambahkan rekening manual atau hubungkan melalui Email Bank.</p>}</div>
      </SettingsSection>
      <SettingsSection eyebrow="GAJI" title="Sumber Slip Gaji Utama" description="Sumber utama menentukan batas Siklus Gaji. Pilih hanya sumber yang benar-benar menjadi pemasukan utama rumah tangga."><select aria-label="Sumber Slip Gaji Utama" value={data.salarySources.find(item => item.isPrimary)?.id || ""} onChange={selectSalary} disabled={!owner || working === "salary-source"}><option value="" disabled>Belum Dipilih</option>{data.salarySources.filter(item => item.active).map(item => <option key={item.id} value={item.id}>{item.employer}</option>)}</select>{data.salarySources.length > 0 && <div className="settings-list">{data.salarySources.map(item => <article key={item.id}><div><b>{item.employer}</b><small>{item.active ? "Aktif" : "Nonaktif"}</small></div><span>{item.isPrimary ? "Utama" : "Cadangan"}</span></article>)}</div>}{!data.salarySources.length && <p className="muted">Belum ada sumber gaji. Konfirmasi slip gaji terlebih dahulu.</p>}</SettingsSection>
      <SettingsSection eyebrow="REKENING DIKENAL" title="Tujuan transfer yang dikenal" description="Petunjuk tersamar membantu membedakan transfer sendiri, keluarga, dan investasi.">
        {owner && <form className="inline-form known-form" onSubmit={createKnown}><input name="institution" placeholder="Institusi, mis. BCA" required/><input name="displayName" placeholder="Nama tampilan" required/><input name="matchHint" placeholder="4+ digit terakhir" minLength="4" required/><select name="relationship" defaultValue="OWN_ACCOUNT"><option value="OWN_ACCOUNT">Rekening sendiri</option><option value="HOUSEHOLD_ACCOUNT">Household</option><option value="INVESTMENT_ACCOUNT">Investasi / RDN</option><option value="OTHER">Lainnya</option></select><select name="userId" defaultValue=""><option value="">Tanpa pemilik khusus</option>{data.members.filter(item => item.active).map(item => <option value={item.id} key={item.id}>{item.displayName}</option>)}</select><button disabled={working === "known-new"}>Tambah</button></form>}
        <div className="settings-list">{data.known.map(item => <article key={item.id}><div><b>{item.displayName}</b><small>{item.institution} · ••••{item.matchHint}</small></div><span>{item.relationship}</span>{owner && <button className={item.active ? "danger" : "secondary"} onClick={() => patch(item.id, `known-accounts/${item.id}`, { active: !item.active })}>{item.active ? "Nonaktifkan" : "Aktifkan"}</button>}</article>)}</div>
      </SettingsSection>
      <SettingsSection eyebrow="EMAIL BANK" title="Notifikasi bank" description="Tambahkan pengirim notifikasi yang dipercaya. Kebijakan semua sumber: Pengeluaran Saja.">
        {owner && <form className="inline-form" onSubmit={createListener}><input name="bankName" placeholder="Nama bank" required/><input name="senderAddress" type="email" placeholder="Alamat pengirim" required/><button disabled={working === "listener-new"}>Tambah</button></form>}
        <div className="settings-list">{data.listeners.map(item => <article key={item.id}><div><b>{item.bankName}</b><small>{item.senderAddress}</small></div><span>{item.active ? "Aktif" : "Nonaktif"} · Pengeluaran Saja</span>{owner && <button className={item.active ? "danger" : "secondary"} onClick={() => patch(item.id, `bank-email-listeners/${item.id}`, { active: !item.active })}>{item.active ? "Nonaktifkan" : "Aktifkan"}</button>}</article>)}</div>
      </SettingsSection>
      <SettingsSection eyebrow="KATEGORI" title="Kategori keluarga" description="Kategori nonaktif tetap tersimpan pada riwayat transaksi.">
        {owner && <form className="inline-form" onSubmit={createCategory}><input name="name" placeholder="Nama kategori" required/><input name="slug" placeholder="slug-kategori" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required/><select name="parentId" defaultValue=""><option value="">Kategori utama</option>{data.categories.filter(item => !item.parentId && item.active).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={working === "category-new"}>Tambah</button></form>}
        <div className="settings-list">{data.categories.map(item => <article key={item.id}><div><b>{item.parentId ? "↳ " : ""}{item.name}</b><small>{item.slug}</small></div><span>{item.active ? "Aktif" : "Nonaktif"}</span>{owner && <div className="row-actions"><button className="secondary" onClick={() => rename(item, "kategori")}>Ubah nama</button><button className={item.active ? "danger" : "secondary"} onClick={() => patch(item.id, `categories/${item.id}`, { active: !item.active })}>{item.active ? "Nonaktifkan" : "Aktifkan"}</button></div>}</article>)}</div>
      </SettingsSection>
      <SettingsSection eyebrow="MERCHANT" title="Aturan kategori otomatis" description="Hanya aturan yang dikonfirmasi secara eksplisit yang dapat aktif.">
        <div className="settings-list">{data.aliases.map(item => <article key={item.id}><div><b>{item.normalizedName}</b><small>Alias: {item.rawName}</small></div><span>{item.defaultCategoryName || "Tanpa kategori"}</span>{owner && <button className={item.autoApply ? "danger" : "secondary"} onClick={() => patch(item.id, `merchant-aliases/${item.id}`, { autoApply: !item.autoApply })}>{item.autoApply ? "Nonaktifkan" : "Aktifkan"}</button>}</article>)}{!data.aliases.length && <p className="empty compact">Belum ada aturan merchant.</p>}</div>
      </SettingsSection>
      <SettingsSection eyebrow="INTEGRASI" title="Email, Telegram, dan gateway" description="Alamat email dibuat Richmod dan aktif hanya setelah pemilik melakukan cutover.">
        <div className="integration-grid"><article><span className={`health-dot ${data.emailIngress?.status === "ACTIVE" ? "ok" : ""}`}/><div><b>Email notifikasi bank</b><small>{data.emailIngress?.address || "Alamat belum dibuat"}{data.emailIngress?.status ? ` · ${data.emailIngress.status}` : ""}{data.emailIngress?.lastReceivedAt ? ` · diterima ${dateTime(data.emailIngress.lastReceivedAt)}` : ""}</small></div><div className="integration-actions">{owner && !data.emailIngress?.address && <button className="secondary" disabled={working === "email-ingress-create"} onClick={() => emailIngressAction()}>Buat alamat</button>}{data.emailIngress?.address && <button className="secondary" onClick={copyEmailIngress}>Salin</button>}{owner && data.emailIngress?.status === "PROVISIONED" && <button disabled={working === "email-ingress-activate"} onClick={() => emailIngressAction("activate")}>Aktifkan</button>}{owner && data.emailIngress?.address && <button className="secondary" disabled={working === "email-ingress-rotate"} onClick={() => window.confirm("Alamat lama akan dinonaktifkan. Lanjutkan?") && emailIngressAction("rotate")}>Rotasi</button>}</div></article><article><span className={`health-dot ${data.members.some(item => item.telegramConnected) ? "ok" : ""}`}/><div><b>Telegram bot</b><small>{data.members.filter(item => item.telegramConnected).length} anggota terhubung</small></div><a className="button secondary" href="/household">Kelola</a></article><article><span className={`health-dot ${data.operations?.worker?.healthy && data.operations?.llmGateway?.configured ? "ok" : ""}`}/><div><b>Worker & LLM gateway</b><small>Worker {data.operations?.worker?.healthy ? "sehat" : "perlu perhatian"} · gateway {data.operations?.llmGateway?.configured ? "terkonfigurasi" : "tidak dikonfigurasi"}</small></div></article></div>
      </SettingsSection>
      <SettingsSection eyebrow="SISTEM" title="Status pemrosesan" description={`Diperiksa ${dateTime(data.operations?.checkedAt)}`}><div className="system-metrics"><article><span>Status</span><b>{data.operations?.status || "—"}</b></article><article><span>Pekerjaan menunggu</span><b>{data.operations?.jobs?.pending ?? "—"}</b></article><article><span>Pekerjaan gagal</span><b>{data.operations?.jobs?.failed ?? "—"}</b></article><article><span>Antrean review</span><b>{data.operations?.reviewBacklog ?? "—"}</b></article></div></SettingsSection>
    </div>
  </AppShell>;
}

function SettingsSection({ eyebrow, title, description, children }) { return <section className="surface settings-section"><div className="settings-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div></div>{children}</section>; }
