"use client";

import Link from "next/link";
import { dateTime, money } from "../lib/format";

const reasons = { AMBIGUOUS_CATEGORY: "Kategori belum pasti", POSSIBLE_DUPLICATE: "Kemungkinan duplikat", UNKNOWN_MERCHANT: "Merchant belum dikenal", UNKNOWN_PURPOSE: "Tujuan belum jelas", TRANSFER_CLASSIFICATION: "Transfer perlu klasifikasi" };

export default function ReviewCards({ items, categories, working, action }) {
  return <div className="review-grid">{items.map(item => item.subjectType ? <CanonicalCard key={item.id} item={item} disabled={working === item.id} action={action}/> : item.type === "UNCLASSIFIED" ? <TransferCard key={item.id} item={item} categories={categories} disabled={working === item.id} action={action}/> : <ReviewCard key={item.id} item={item} categories={categories} disabled={working === item.id} action={action}/>)}{!items.length && <div className="empty-state"><span>✓</span><h2>Perlu Ditinjau sudah bersih</h2><p>Tidak ada transaksi yang membutuhkan keputusan saat ini.</p></div>}</div>;
}

function CanonicalCard({ item, disabled, action }) {
  const payslip = item.reviewType === "PAYSLIP_CONFIRMATION"; const missingDate = item.reviewType === "MISSING_PAY_DATE";
  function resolve(actionName, values = {}) { action(item.id, "resolve", { action: actionName, values }); }
  function submitDate(event) { event.preventDefault(); const form = new FormData(event.currentTarget); resolve("SET_PAY_DATE", { payDate: form.get("payDate"), choice: form.get("choice") }); }
  return <article className="review-card"><div className="review-top"><span className="review-reason">{item.reviewType.replaceAll("_", " ")}</span></div><h2>{item.description || "Bukti keuangan perlu ditinjau"}</h2><p>Keputusan ini tersimpan pada Review Inbox dan berlaku juga untuk Telegram.</p>{payslip && <div className="transfer-options"><button disabled={disabled} onClick={() => resolve("PRIMARY_SALARY")}>Jadikan gaji utama</button><button disabled={disabled} onClick={() => resolve("ORDINARY_INCOME")}>Catat pemasukan biasa</button><button className="danger" disabled={disabled} onClick={() => resolve("IGNORE")}>Abaikan</button></div>}{missingDate && <form onSubmit={submitDate}><label>Tanggal pembayaran<input name="payDate" type="date" required/></label><label>Catat sebagai<select name="choice" defaultValue="ORDINARY_INCOME"><option value="ORDINARY_INCOME">Pemasukan biasa</option><option value="PRIMARY_SALARY">Gaji utama</option></select></label><div className="review-actions"><button disabled={disabled}>Simpan dan konfirmasi</button><button type="button" className="danger" disabled={disabled} onClick={() => resolve("IGNORE")}>Abaikan</button></div></form>}{!payslip && !missingDate && <div className="review-actions"><button disabled={disabled} onClick={() => resolve("CONFIRM")}>Konfirmasi</button><button className="danger" disabled={disabled} onClick={() => resolve("IGNORE")}>Abaikan</button></div>}</article>;
}

function ReviewCard({ item, categories, disabled, action }) {
  function confirm(event) { event.preventDefault(); const form = new FormData(event.currentTarget); action(item.id, "confirm", { categoryId: form.get("categoryId") || null, note: form.get("note") || null, rememberMerchant: form.get("rememberMerchant") === "on" }); }
  const proposal = item.proposalStatus === "NEEDS_REVIEW" ? "Perlu Ditinjau" : (item.proposalStatus || "Perlu Ditinjau");
  return <article className="review-card"><div className="review-top"><span className="review-reason">{reasons[item.reason] || item.reason}</span><strong>{money(item.amount)}</strong></div><h2>{item.merchantName || item.counterparty || item.description || "Transaksi tanpa keterangan"}</h2><p>{dateTime(item.transactionAt)} · {item.sourceType || "Input"}</p><div className="state-line"><span>Status: Perlu Ditinjau</span><span>Usulan: {proposal}</span></div>{item.candidates?.length > 0 && <div className="candidates"><b>Kemungkinan sama dengan</b>{item.candidates.map(candidate => <button type="button" disabled={disabled} key={candidate.id} onClick={() => action(item.id, "merge", { targetTransactionId: candidate.id })}><span>{candidate.description || "Transaksi sebelumnya"}</span><strong>{Math.round(candidate.score * 100)}% cocok</strong></button>)}</div>}<form onSubmit={confirm}><label>Kategori<select name="categoryId" defaultValue={item.categoryId || ""} required={item.type === "EXPENSE"}><option value="" disabled>Pilih kategori</option>{categories.filter(category => category.active).map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Catatan opsional<input name="note" defaultValue={item.note || ""} maxLength="1000"/></label>{item.type === "EXPENSE" && item.merchantName && <label className="check"><input name="rememberMerchant" type="checkbox"/> Ingat kategori untuk merchant ini</label>}<div className="review-actions"><button disabled={disabled}>Konfirmasi</button><button className="danger" type="button" disabled={disabled} onClick={() => action(item.id, "reject")}>Abaikan</button><Link className="button secondary" href={`/transactions?id=${item.id}`}>Buka Bukti</Link></div></form></article>;
}

function TransferCard({ item, categories, disabled, action }) {
  function expense(event) { event.preventDefault(); const form = new FormData(event.currentTarget); action(item.id, "classify-transfer", { classification: "EXPENSE", categoryId: form.get("categoryId") }); }
  return <article className="review-card transfer-card"><div className="review-top"><span className="review-reason">TRANSFER BELUM DIKENAL</span><strong>{money(item.amount)}</strong></div><h2>{item.counterparty || "Tujuan transfer belum dikenal"}</h2><p>{dateTime(item.transactionAt)} · belum dihitung sebagai pengeluaran</p><div className="state-line"><span>Status: Belum Diklasifikasikan</span><span>Usulan: Perlu Ditinjau</span></div><div className="transfer-options"><button disabled={disabled} onClick={() => action(item.id, "classify-transfer", { classification: "OWN_ACCOUNT" })}>Rekening sendiri</button><button disabled={disabled} onClick={() => action(item.id, "classify-transfer", { classification: "HOUSEHOLD_ACCOUNT" })}>Rekening rumah tangga</button><button disabled={disabled} onClick={() => action(item.id, "classify-transfer", { classification: "INVESTMENT_ACCOUNT" })}>Investasi / RDN</button><button className="danger" disabled={disabled} onClick={() => action(item.id, "classify-transfer", { classification: "IGNORE" })}>Abaikan</button></div><form onSubmit={expense}><label>Jika ini pengeluaran<select name="categoryId" required defaultValue=""><option value="" disabled>Pilih kategori</option>{categories.filter(category => category.active).map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><div className="review-actions"><button disabled={disabled}>Catat sebagai pengeluaran</button><Link className="button secondary" href={`/transactions?id=${item.id}`}>Buka Bukti</Link></div></form></article>;
}
